dbHost: localhost
dbPort: 3306
dbCatalog: omniscient
dbUser: omniscient
dbPassword: typePasswordHere
blockLimitsEnabled: true
blockStatsEnabled: true
autoWhiteListOff: true
autoWhiteListOffDelaySeconds: 120
scanChunksOnLoad: true
scanChunksPeriodicallyEnabled: true
scanChunksPeriodicallyDelaySeconds: 300
scanChunksPeriodicallyIntervalSeconds: 300
scanChunksMinimumIntervalForSameChunkSeconds: 60
autoRemoveUnknownBlocksEnabled: false
autoReplaceUnknownBlocksEnabled: false
autoReplaceUnknownBlocksId: 3
autoReplaceUnknownBlocksSubValue: 0
autoReplaceUnknownBlocksWithSignEnabled: true
autoSync: true
enablePlayerInfoOnBlockEvents: true
devUser: unlessYourMeJustLeaveThisAlone
